// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// set_ZD
NumericVector set_ZD(NumericMatrix Z, NumericVector D);
RcppExport SEXP BATools_set_ZD(SEXP ZSEXP, SEXP DSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type D(DSEXP);
    rcpp_result_gen = Rcpp::wrap(set_ZD(Z, D));
    return rcpp_result_gen;
END_RCPP
}
// get_pvalue
NumericMatrix get_pvalue(NumericVector U, NumericVector V, NumericMatrix G, NumericMatrix Z, NumericMatrix X);
RcppExport SEXP BATools_get_pvalue(SEXP USEXP, SEXP VSEXP, SEXP GSEXP, SEXP ZSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type U(USEXP);
    Rcpp::traits::input_parameter< NumericVector >::type V(VSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type G(GSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(get_pvalue(U, V, G, Z, X));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP BayesACL(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP BayesBC(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP BayesCC(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"BATools_set_ZD", (DL_FUNC) &BATools_set_ZD, 2},
    {"BATools_get_pvalue", (DL_FUNC) &BATools_get_pvalue, 5},
    {"BayesACL",           (DL_FUNC) &BayesACL,            9},
    {"BayesBC",            (DL_FUNC) &BayesBC,            16},
    {"BayesCC",            (DL_FUNC) &BayesCC,            13},
    {NULL, NULL, 0}
};

RcppExport void R_init_BATools(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
