# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

set_ZD <- function(Z, D) {
    .Call('BATools_set_ZD', PACKAGE = 'BATools', Z, D)
}

