#'  A print method for ba objects
#'  @title print \code{\link{ba}} object
#'  @param ba an object of the class ba generated by \code{\link{bafit}}
#'  @return Null. This function only prints to the screen.
#'  @export
#'  
print.ba <- function(ba) {    
    cat("BATools analysis of trait:", ba$trait, "\n")    
    cat("\nestimated fixed effects:\n")
    print(ba$betahat)
    cat("\nestimated hyperparameters:\n")
    print(ba$hyper_est)
    if(!is.null(ba$eff_sample)) {
	cat("\neffective sample size for hyperparameters: \n")
	print(ba$eff_sample)
    }
}





rankMatrix<-function (x, tol = NULL, method = c("tolNorm2", "qr.R", "qrLINPACK", 
    "qr", "useGrad", "maybeGrad"), sval = svd(x, 0, 0)$d, warn.t = TRUE) 
{
    stopifnot(length(d <- dim(x)) == 2)
    p <- min(d)
    method <- match.arg(method)
    if (useGrad <- (method %in% c("useGrad", "maybeGrad"))) {
        stopifnot(length(sval) == p, diff(sval) <= 0)
        ln.av <- log(abs(sval))
        diff1 <- diff(ln.av)
        if (method == "maybeGrad") {
            grad <- (min(ln.av) - max(ln.av))/p
            useGrad <- (min(diff1) <= min(-3, 10 * grad))
        }
    }
    if (!useGrad) {
        x.dense <- is.numeric(x) || is(x, "denseMatrix")
        if ((Meth <- method) == "qr") 
            method <- if (x.dense) 
                "qrLINPACK"
            else "qr.R"
        else Meth <- substr(method, 1, 2)
        if (Meth == "qr") {
            if (is.null(tol)) 
                tol <- max(d) * .Machine$double.eps
        }
        else {
            if (is.null(tol)) {
                if (!x.dense && missing(sval) && prod(d) >= 100000L) 
                  warning(gettextf("rankMatrix(<large sparse Matrix>, method = '%s') coerces to dense matrix.\n Probably should rather use method = 'qr' !?", 
                    method), immediate. = TRUE, domain = NA)
                stopifnot(diff(sval) <= 0)
                tol <- max(d) * .Machine$double.eps
            }
            else stopifnot((tol <- as.numeric(tol)[[1]]) >= 0)
        }
    }
    structure(if (useGrad) 
        which.min(diff1)
    else if (Meth == "qr") {
        if ((do.t <- (d[1L] < d[2L])) && warn.t) 
            warning(gettextf("rankMatrix(x, method='qr'): computing t(x) as nrow(x) < ncol(x)"))
        q.r <- qr(if (do.t) 
            t(x)
        else x, tol = tol, LAPACK = method != "qrLINPACK")
        if (x.dense && (method == "qrLINPACK")) 
            q.r$rank
        else {
            diagR <- if (x.dense) 
                diag(q.r$qr)
            else diag(q.r@R)
            d.i <- abs(diagR)
            sum(d.i >= tol * max(d.i))
        }
    }
    else sum(sval >= tol * sval[1]), method = method, useGrad = useGrad, 
        tol = if (useGrad) 
            NA
        else tol)
}
